### ISSUE TITLE
Three missing surface flow sites

### ISSUE THREAD

**Issue by LucyJordan** [UGS-GIO/groundwaterMonPortal#47] opened 2022-12-07 22:23 UTC
### What happened?

About 2 years ago, at the request of DWR and a few public users, we added three surface flow measuring sites to the data portal that we collect only periodic spot flow measurements on. The sites are
LocationID GageName
10014	WARM CREEK NEAR GANDY (SPRING)
10015	Big Springs South Channel
10016	Big Springs North Channel

The sites do not even show up as symbols on the map anymore. This makes it impossible to access the data.

### What did you expect to happen?

Should be able to see, click, and download data from the map interface, just like the other surface flow sites.

### Browser Version

Chrome Version 108.0.5359.95 (Official Build) (64-bit)

**Comment by inkenbrandt** [comment] 2022-12-07 22:32
Rooted in Issues 42 and 13 https://github.com/UGS-GIO/groundwaterMonPortal/issues/42

**Comment by inkenbrandt** [comment] 2022-12-07 22:35
This issue was caused by resolving issue 14 (https://github.com/UGS-GIO/groundwaterMonPortal/issues/14).  I will go into the `monitoringlocations` table and re-enable these sites to show them again.

**Closed** 2023-01-09 16:10 UTC
Labels: bug
